import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

# import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [3]:
tips.head(10)

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
5,25.29,4.71,Male,No,Sun,Dinner,4
6,8.77,2.00,Male,No,Sun,Dinner,2
7,26.88,3.12,Male,No,Sun,Dinner,4
8,15.04,1.96,Male,No,Sun,Dinner,2
9,14.78,3.23,Male,No,Sun,Dinner,2


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [4]:
m= np.array([1,2,3,4])
n= np.array([[1,2,3,4],[5,6,7,8]])
o= np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])
p= np.array([[[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]],[[[11,22,33,44],[55,66,77,88]],[[100,200,300,400],[500,600,700,800]]]])
m,n,o,p,[arr.ndim for arr in (m, n, o, p)] ,[arr.shape for arr in (m, n, o, p)]



(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[10, 20, 30, 40],
         [50, 60, 70, 80]]]),
 array([[[[  1,   2,   3,   4],
          [  5,   6,   7,   8]],
 
         [[ 10,  20,  30,  40],
          [ 50,  60,  70,  80]]],
 
 
        [[[ 11,  22,  33,  44],
          [ 55,  66,  77,  88]],
 
         [[100, 200, 300, 400],
          [500, 600, 700, 800]]]]),
 [1, 2, 3, 4],
 [(4,), (2, 4), (2, 2, 4), (2, 2, 2, 4)])

# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [5]:
m1 = np.arange(4)
n1 = np.arange(8).reshape(2,4)
o1 = np.arange(16).reshape(2,2,4)
p1 = np.arange(32).reshape(2,2,2,4)

m1,n1,o1,p1

(array([0, 1, 2, 3]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]),
 array([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7]],
 
         [[ 8,  9, 10, 11],
          [12, 13, 14, 15]]],
 
 
        [[[16, 17, 18, 19],
          [20, 21, 22, 23]],
 
         [[24, 25, 26, 27],
          [28, 29, 30, 31]]]]))

# create array using ones and zeros

In [6]:
np.zeros((2,4)), np.ones((2,2,4))

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

# using random

In [7]:
np.random.randint(1,100,size=(2,3,4))

array([[[30, 86, 62,  5],
        [82,  2, 26,  1],
        [82, 50, 13, 34]],

       [[ 3,  4, 81, 53],
        [73, 36,  9, 68],
        [70, 40,  2, 28]]])

# using linspace

In [8]:
np.linspace(10,1000,99,dtype=int).reshape(11,9)

array([[  10,   20,   30,   40,   50,   60,   70,   80,   90],
       [ 100,  111,  121,  131,  141,  151,  161,  171,  181],
       [ 191,  201,  212,  222,  232,  242,  252,  262,  272],
       [ 282,  292,  302,  313,  323,  333,  343,  353,  363],
       [ 373,  383,  393,  403,  414,  424,  434,  444,  454],
       [ 464,  474,  484,  494,  505,  515,  525,  535,  545],
       [ 555,  565,  575,  585,  595,  606,  616,  626,  636],
       [ 646,  656,  666,  676,  686,  696,  707,  717,  727],
       [ 737,  747,  757,  767,  777,  787,  797,  808,  818],
       [ 828,  838,  848,  858,  868,  878,  888,  898,  909],
       [ 919,  929,  939,  949,  959,  969,  979,  989, 1000]])

# create 1D array of tip from tips dataframe

In [9]:
tips['tip'].to_numpy()

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

# create 2D array of tip and total_bill form tips dataframe

In [10]:
tips[['tip','total_bill']].to_numpy()

array([[ 1.01, 16.99],
       [ 1.66, 10.34],
       [ 3.5 , 21.01],
       [ 3.31, 23.68],
       [ 3.61, 24.59],
       [ 4.71, 25.29],
       [ 2.  ,  8.77],
       [ 3.12, 26.88],
       [ 1.96, 15.04],
       [ 3.23, 14.78],
       [ 1.71, 10.27],
       [ 5.  , 35.26],
       [ 1.57, 15.42],
       [ 3.  , 18.43],
       [ 3.02, 14.83],
       [ 3.92, 21.58],
       [ 1.67, 10.33],
       [ 3.71, 16.29],
       [ 3.5 , 16.97],
       [ 3.35, 20.65],
       [ 4.08, 17.92],
       [ 2.75, 20.29],
       [ 2.23, 15.77],
       [ 7.58, 39.42],
       [ 3.18, 19.82],
       [ 2.34, 17.81],
       [ 2.  , 13.37],
       [ 2.  , 12.69],
       [ 4.3 , 21.7 ],
       [ 3.  , 19.65],
       [ 1.45,  9.55],
       [ 2.5 , 18.35],
       [ 3.  , 15.06],
       [ 2.45, 20.69],
       [ 3.27, 17.78],
       [ 3.6 , 24.06],
       [ 2.  , 16.31],
       [ 3.07, 16.93],
       [ 2.31, 18.69],
       [ 5.  , 31.27],
       [ 2.24, 16.04],
       [ 2.54, 17.46],
       [ 3.06, 13.94],
       [ 1.

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [11]:
print("n -> ndim:",n.ndim," shape:",n.shape," size:",n.size," itemsize:",n.itemsize)
print("o -> ndim:",o.ndim," shape:",o.shape," size:",o.size," itemsize:",o.itemsize)
print("m1 -> ndim:",m1.ndim," shape:",m1.shape," size:",m1.size," itemsize:",m1.itemsize)
print("p1 -> ndim:",p1.ndim," shape:",p1.shape," size:",p1.size," itemsize:",p1.itemsize)


n -> ndim: 2  shape: (2, 4)  size: 8  itemsize: 8
o -> ndim: 3  shape: (2, 2, 4)  size: 16  itemsize: 8
m1 -> ndim: 1  shape: (4,)  size: 4  itemsize: 8
p1 -> ndim: 4  shape: (2, 2, 2, 4)  size: 32  itemsize: 8


# change data type and memory size of any np-array using astype()

In [12]:
m_fl=m.astype(np.float32)
print("m_int=",m.itemsize," m_float=",m_fl.itemsize)

m_int= 8  m_float= 4


In [13]:
scalar= m*n
vector= m+n
print(m,"\n",n,"\nScalar:\n",m*n,"\nVector:\n",m+n)

[1 2 3 4] 
 [[1 2 3 4]
 [5 6 7 8]] 
Scalar:
 [[ 1  4  9 16]
 [ 5 12 21 32]] 
Vector:
 [[ 2  4  6  8]
 [ 6  8 10 12]]


# find minimun and maximum tip

In [14]:
print(f"Min Tip: {np.min(tips['tip'].to_numpy())}, Max Tip: {np.max(tips['tip'].to_numpy())}")

Min Tip: 1.0, Max Tip: 10.0


# find average total_bill and average tip

In [15]:
print(f"Average Total Bill: {np.mean(tips['total_bill'].to_numpy()):.2f}")
print(f"Average Tip: {np.mean(tips['tip'].to_numpy()):.2f}")

Average Total Bill: 19.79
Average Tip: 3.00


# find median total_bill

In [16]:
print(f"Median Total Bill: {np.median(tips['total_bill'].to_numpy())}")

Median Total Bill: 17.795


# find standard deviasion and variance of tip

In [17]:
print(f"standard deviasion: {np.std(tips['tip'].to_numpy()):.2f}")
print(f"standard variance: {np.var(tips['tip'].to_numpy()):.2f}")

standard deviasion: 1.38
standard variance: 1.91


# find log values of tip

In [18]:
np.log(tips['tip'].to_numpy())

array([0.00995033, 0.5068176 , 1.25276297, 1.19694819, 1.28370777,
       1.54968791, 0.69314718, 1.137833  , 0.67294447, 1.17248214,
       0.53649337, 1.60943791, 0.45107562, 1.09861229, 1.10525683,
       1.36609165, 0.51282363, 1.31103188, 1.25276297, 1.20896035,
       1.40609699, 1.01160091, 0.80200159, 2.0255132 , 1.1568812 ,
       0.85015093, 0.69314718, 0.69314718, 1.45861502, 1.09861229,
       0.37156356, 0.91629073, 1.09861229, 0.89608802, 1.18478998,
       1.28093385, 0.69314718, 1.12167756, 0.83724752, 1.60943791,
       0.80647587, 0.93216408, 1.11841492, 0.27763174, 1.7227666 ,
       1.09861229, 1.60943791, 1.79175947, 0.71783979, 1.09861229,
       0.91629073, 0.95551145, 1.64865863, 0.44468582, 1.46787435,
       1.25561604, 1.09861229, 0.40546511, 0.56531381, 1.90657514,
       1.16627094, 0.69314718, 0.68309684, 1.32441896, 0.97077892,
       1.14740245, 0.90421815, 0.        , 0.69813472, 0.73716407,
       0.67803354, 1.09861229, 1.1442228 , 1.60943791, 0.78845

# apply round, floor and ceil operation on tip array

In [19]:
print(f"rounded tip: {np.round(tips['tip'].to_numpy())}")
print(f"floored tip: {np.floor(tips['tip'].to_numpy())}")
print(f"ceiled tip: {np.ceil(tips['tip'].to_numpy())}")

rounded tip: [ 1.  2.  4.  3.  4.  5.  2.  3.  2.  3.  2.  5.  2.  3.  3.  4.  2.  4.
  4.  3.  4.  3.  2.  8.  3.  2.  2.  2.  4.  3.  1.  2.  3.  2.  3.  4.
  2.  3.  2.  5.  2.  3.  3.  1.  6.  3.  5.  6.  2.  3.  2.  3.  5.  2.
  4.  4.  3.  2.  2.  7.  3.  2.  2.  4.  3.  3.  2.  1.  2.  2.  2.  3.
  3.  5.  2.  1.  3.  4.  3.  3.  3.  3.  2.  5.  2.  5.  2.  4.  6.  3.
  3.  4.  1.  4.  3.  5.  4.  2.  3.  2.  2.  3.  2.  3.  4.  2.  4.  4.
  4.  4.  3.  1.  4.  3.  4.  4.  5.  2.  2.  3.  2.  2.  2.  2.  3.  4.
  1.  2.  2.  2.  2.  3.  2.  2.  3.  1.  2.  2.  2.  3.  4.  7.  5.  5.
  2.  2.  1.  2.  2.  2.  2.  2.  3.  2.  2.  5.  5.  4.  3.  2.  4.  2.
  2.  2.  3.  3.  2.  4.  2.  2. 10.  3.  5.  3.  4.  3.  2.  2.  4.  4.
  4.  6.  4.  6.  3.  5.  4.  2.  4.  4.  2.  4.  3.  2.  4.  1.  2.  5.
  2.  2.  4.  2.  2.  2.  4.  3.  3.  3.  2.  2.  2.  5.  9.  2.  6.  1.
  3.  2.  1.  3.  2.  3.  2.  3.  2.  2.  2.  3.  3.  3.  2.  3.  3.  1.
  3.  1.  1.  1.  5.  6.  2.  2.  2.  

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [20]:
print(m[0],m[-1],m[1:3],m[:2],m[::2])
print(n[0,1],n[1,:],n[:,2],n[0:2,1:3],n[:,::2])
print(o[0,1,2],o[0],o[:,0,:],o[1,:,3],o[:,:,1:3])

1 4 [2 3] [1 2] [1 3]
2 [5 6 7 8] [3 7] [[2 3]
 [6 7]] [[1 3]
 [5 7]]
7 [[1 2 3 4]
 [5 6 7 8]] [[ 1  2  3  4]
 [10 20 30 40]] [40 80] [[[ 2  3]
  [ 6  7]]

 [[20 30]
  [60 70]]]


# stacking and spliting

# use hstack() and vstack()

In [21]:
np.hstack((n,n)),np.vstack((o,o))

(array([[1, 2, 3, 4, 1, 2, 3, 4],
        [5, 6, 7, 8, 5, 6, 7, 8]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[10, 20, 30, 40],
         [50, 60, 70, 80]],
 
        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[10, 20, 30, 40],
         [50, 60, 70, 80]]]))

# use hsplit() and vsplit()

In [22]:
np.hsplit(n,2),np.vsplit(o,2)

([array([[1, 2],
         [5, 6]]),
  array([[3, 4],
         [7, 8]])],
 [array([[[1, 2, 3, 4],
          [5, 6, 7, 8]]]),
  array([[[10, 20, 30, 40],
          [50, 60, 70, 80]]])])